export default [
  {
    title: '布局字段',
    list: [{
      type: 'dynamic',
      label: '子表单',
      icon: 'table',
      span: 24,
      display: true,
      children: {
        align: 'center',
        headerAlign: 'center',
        addBtn: true,
        delBtn: true,
        column: [],
      },
    }, {
      type: 'divider',
      span: 24,
      label: '换行',
      display: true,
    }, {
      type: 'slot',
      span: 24,
      label: '插槽',
      slotName: '',
    }],
  },
  {
    title: '输入字段',
    list: [{
      type: 'single-input',
      label: '单行文本',
      icon: 'icon-input',
      span: 24,
      display: true,
    }, {
      type: 'password',
      label: '密码',
      icon: 'icon-password',
      span: 24,
      display: true,
    }, {
      type: 'multi-input',
      label: '多行文本',
      icon: 'icon-textarea',
      span: 24,
      display: true,
    }, {
      type: 'number',
      label: '计数器',
      icon: 'icon-number',
      span: 24,
      display: true,
    }],
  },
  {
    title: '选择字段',
    list: [{
      type: 'switch',
      label: '开关',
      icon: 'icon-switch',
      span: 24,
      display: true,
      valueDefault: 0,
    }, {
      type: 'radio',
      label: '单选框组',
      icon: 'icon-radio',
      dataType: 'static',
      collectionType: '',
      collectionFilter: '',
      reverseFilter: false,
      staticData: [
        { label: '选项一', value: '0', },
        { label: '选项二', value: '1', },
        { label: '选项三', value: '2', }
      ],
      span: 24,
      display: true,
    }, {
      type: 'checkbox',
      label: '多选框组',
      icon: 'icon-checkbox',
      dataType: 'static',
      staticData: [
        { label: '选项一', value: '0', },
        { label: '选项二', value: '1', },
        { label: '选项三', value: '2', }
      ],
      span: 24,
      display: true,
    }, {
      type: 'select',
      label: '下拉选择器',
      icon: 'icon-select',
      dataType: 'static',
      staticData: [
        { label: '选项一', value: '0', },
        { label: '选项二', value: '1', },
        { label: '选项三', value: '2', }
      ],
      span: 24,
      mode: 'default',
      display: true,
      allowClear: true,
    }, {
      type: 'cascader',
      label: '级联选择器',
      icon: 'icon-link',
      span: 24,
      dataType: 'static',
      allowClear: true,
      changeOnSelect: true,
      display: true,
      expandTrigger: 'click',
      staticData: [
        {
          label: '选项一',
          value: '1',
          id: '1',
          children: [{
            label: '选项1-1',
            value: '1-1',
            id: '1-1',
          }, {
            label: '选项1-2',
            value: '1-2',
            id: '1-2',
          }],
        },
        { label: '选项二', value: '2', id: '2', },
        { label: '选项三', value: '3', id: '3', }
      ],
    }, {
      type: 'tree',
      label: '树形选择器',
      icon: 'icon-tree',
      span: 24,
      dataType: 'static',
      allowClear: true,
      display: true,
      staticData: [
        {
          label: '选项一',
          value: '1',
          id: '1',
          children: [{
            label: '选项1-1',
            value: '1-1',
            id: '1-1',
          }, {
            label: '选项1-2',
            value: '1-2',
            id: '1-2',
          }],
        },
        { label: '选项二', value: '2', id: '2', },
        { label: '选项三', value: '3', id: '3', }
      ],
    }],
  }, {
    title: '日期时间字段',
    list: [{
      type: 'year',
      label: '年',
      icon: 'icon-year',
      span: 24,
      display: true,
      allowClear: true,
      validNowTime: '-1',
      format: 'YYYY',
    }, {
      type: 'quarter',
      label: '季度',
      icon: 'icon-quarter',
      span: 24,
      display: true,
      allowClear: true,
      format: 'YYYY-第Q季度',
      validNowTime: '-1',
    }, {
      type: 'month',
      label: '月',
      icon: 'icon-month',
      span: 24,
      display: true,
      allowClear: true,
      format: 'YYYY-MM',
      validNowTime: '-1',
    }, {
      type: 'week',
      label: '周',
      icon: 'icon-week',
      span: 24,
      display: true,
      allowClear: true,
      format: 'YYYY-第ww周',
      validNowTime: '-1',
    }, {
      type: 'date',
      label: '日期',
      icon: 'icon-date',
      span: 24,
      display: true,
      allowClear: true,
      format: 'YYYY-MM-DD',
      showToday: true,
      validNowTime: '-1',
    }, {
      type: 'time',
      label: '时间',
      icon: 'icon-time',
      span: 24,
      display: true,
      allowClear: true,
      format: 'HH:mm:ss',
      validNowTime: '-1',
    }, {
      type: 'datetime',
      label: '日期时间',
      icon: 'icon-datetime',
      span: 24,
      display: true,
      allowClear: true,
      format: 'YYYY-MM-DD HH:mm:ss',
      validNowTime: '-1',
    }, {
      type: 'daterange',
      label: '日期范围',
      icon: 'icon-date-range',
      span: 24,
      allowClear: true,
      display: true,
      format: 'YYYY-MM-DD',
      validNowTime: '-1',
    }, {
      type: 'datetimerange',
      label: '日期时间范围',
      icon: 'icon-datetime-range',
      span: 24,
      allowClear: true,
      display: true,
      format: 'YYYY-MM-DD HH:mm:ss',
      validNowTime: '-1',
    }],
  },
  {
    title: '其他字段',
    list: [{
      type: 'rate',
      label: '评价',
      icon: 'icon-star',
      span: 24,
      display: true,
    }, {
      type: 'slider',
      label: '滑块',
      icon: 'icon-slider',
      span: 24,
      display: true,
      range: false,
      step: 1,
      min: 0,
      max: 10,
    }, {
      type: 'color',
      label: '颜色选择器',
      icon: 'icon-color',
      span: 24,
      display: true,
      panelPosition: 'left',
      verticalPosition: 'bottom',
      initialValue: '#000000',
    }],
  }
]
